# Generated by Django 6.0.4 on 2026-04-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_courier_deliveries_count_courier_earnings_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
