# Generated by Django 6.0.4 on 2026-04-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courier',
            name='delivery_history',
            field=models.ManyToManyField(blank=True, related_name='delivered_by', to='api.order'),
        ),
    ]
