from django.core.management.base import BaseCommand
from api.models import Restaurant, MenuItem


RESTAURANTS = [
    # ── RESTAURANTS ──
    {
        "name": "Casa Bento",
        "description": "Popular restaurant in Al Hoceima city center with bento-style dishes.",
        "address": "25 Av. Hassan II",
        "city": "Al Hoceima",
        "phone": "+212 539 000 001",
        "category": "Restaurant",
        "rating": 4.3,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE22vN_YCYZfhB-Ay3HaN14eD4NgQiYRPOBKpnn-KNb8VBzG_mnjzL3mectz2p1rLjDuwxrDJx01ls0jH21Et6I_DIvksx56zU1mGFcZTmZUo4sruAxjgPyflju-pgfL9Pl9E30=w400-h400-n-k-no",
        "delivery_time": "20-35 min",
        "delivery_fee": 15,
    },
    {
        "name": "Lunamar Express",
        "description": "Fresh food and quick bites on Bd Tarik Ibn Ziyad.",
        "address": "58 Bd Tarik Ibn Ziyad",
        "city": "Al Hoceima",
        "phone": "+212 539 000 002",
        "category": "Restaurant",
        "rating": 4.1,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGmQHYVYx2_5iPy5RNr9QfvEgSKVzzY_v7uptIsSYZmQPc7jszrC4hBIpY-bNJrS78vf1I5XTDqHFAOWfNtBXrvUWWaL75LtPCjZUUIdGsKHdVWJYBxB3tWVOjueBJgXuVjUY513g=w400-h400-n-k-no",
        "delivery_time": "25-40 min",
        "delivery_fee": 15,
    },
    {
        "name": "CLASSIC FOOD",
        "description": "Classic Moroccan dishes and fast bites at affordable prices.",
        "address": "30 Rue Moulay Idriss al Akbar",
        "city": "Al Hoceima",
        "phone": "+212 539 000 003",
        "category": "Restaurant",
        "rating": 3.7,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGJadhNKnUAMUHORUku_bSqzqxpxD5GohbYQhagFXrYDrIp1rEIF-eArD_UZt8m1_NM_BYf7u_6m_4BJWTxuEhOL2DwGgDAo3opLzFVJ4W2r9M0CVXGltEF2A-fApz6Pnm7He2G=w400-h400-n-k-no",
        "delivery_time": "20-30 min",
        "delivery_fee": 10,
    },
    {
        "name": "تاكوس الحسيمة",
        "description": "Best tacos in Al Hoceima — halal & fresh with amazing sauces.",
        "address": "34 Rue Algérie",
        "city": "Al Hoceima",
        "phone": "+212 539 000 004",
        "category": "Fast Food",
        "rating": 4.7,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAETCONf5HxrI3-UR7INZZC0QzduYPhYyyaZJnQfrDsPz1AwNVzNVplxT6MBapL9ynOn8zJSGhBBq64razn6pDLJcphVz1wHMwtusinbBBzJQZd3N7FubGVSMFnzxAYsySyG8nFZNg=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 10,
    },
    {
        "name": "Wok in Al Hoceima",
        "description": "Asian fusion and wok dishes — unique flavours in Al Hoceima.",
        "address": "Bd Abdelkrim El Khattabi",
        "city": "Al Hoceima",
        "phone": "+212 539 000 005",
        "category": "Restaurant",
        "rating": 3.5,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGymoNads33yumsClQmWCN5DVmtz3q0A5EtaeKdiAQd2HatsfOeXu52hs7RFo0cb7Y8-X_shEaEu0QY9KBiizWrvS1UzT3-SrbeObWTx_V9dCAsttbfHq-3CofNYpCxIgj_Dj71=w400-h400-n-k-no",
        "delivery_time": "30-45 min",
        "delivery_fee": 20,
    },
    {
        "name": "Rico",
        "description": "Top-rated BBQ & grills — the most popular grill in town.",
        "address": "Av. Sidi Abid",
        "city": "Al Hoceima",
        "phone": "+212 539 000 006",
        "category": "Barbecue",
        "rating": 4.9,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEtEzUef_4bYmgDkLx-jpdyjwxy42Mzkrxtd7S9BtLArukZjKerwYPYH75WH4J64tE__Sjr3ScUzh9ZnzTdFR6qX7F5aWlUinwrHNSTw9cSXPSbJvtZfLBi87sD5lvHiqm0_pY=w400-h400-n-k-no",
        "delivery_time": "20-35 min",
        "delivery_fee": 15,
    },
    {
        "name": "Boom Burger",
        "description": "Juicy smash burgers and crispy fries — fast delivery guaranteed.",
        "address": "Al Hoceima centre",
        "city": "Al Hoceima",
        "phone": "+212 539 000 007",
        "category": "Fast Food",
        "rating": 3.7,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEPXNThnXhEJ14i4ZOhdf_jELO6-9opNeLdHkhye-nl8bszOoCpOhv5bUw8G7C3N9E2AjwHjBg_kG6hGItn48N0BJuYbY_W3Y0aW9EXTE0744I8YHj1yTlfD4aD67J794n06r1kHw=w400-h400-n-k-no",
        "delivery_time": "20-30 min",
        "delivery_fee": 10,
    },
    {
        "name": "BRIMO CHICKEN",
        "description": "Crispy fried chicken, sandwiches and wraps.",
        "address": "Rue Hajra Nekour",
        "city": "Al Hoceima",
        "phone": "+212 539 000 008",
        "category": "Fast Food",
        "rating": 3.9,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEMWWHEEteeTOYLhwDaF2yFo3jbt9m8GXm5bAludSs-OJ3Zs6km3YTfV9SarZP_oMgLgRVCgM4gLvNQlLxG-z4QEO6QDQDWcVP6QTdQQHKJ8OkID_ZCa8EAvf4bfkKJH8RLXICi5A=w400-h400-n-k-no",
        "delivery_time": "20-30 min",
        "delivery_fee": 10,
    },
    {
        "name": "Coin BBQ",
        "description": "Grills & BBQ open all day and all night on Av. Mohamed V.",
        "address": "114 Av. Mohamed V",
        "city": "Al Hoceima",
        "phone": "+212 539 000 009",
        "category": "Barbecue",
        "rating": 4.3,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF81vquy1xiSG7wiQwSTj6nqZoSGKy9KahBYW2yDoU8VZDuxC-_z87t9gQBC_NYvytjZvXpqzTbs3PlD_JJuQKvMC1r53psOOkojl36HLUqxDY09rY3qFmBgrlnkQUxMFbEpQbUV-iQ3LIo=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 0,
    },
    {
        "name": "Thuishaven",
        "description": "Evening bites and fast food until 3 AM — open late!",
        "address": "Al Hoceima",
        "city": "Al Hoceima",
        "phone": "+212 539 000 010",
        "category": "Fast Food",
        "rating": 4.7,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEvQ0MY5V8QSBzX82u9mXkDgnRKTnBSQg2Rf6mt1rXIkw4diB6_ecwDir1FFxapYIISidBZjGX-Eag5mzKbJ0jHInBwPsT9UHfKcTtwKQC3ODJcgA7wV3x179hhhLt0WJAZeGQFLg=w400-h400-n-k-no",
        "delivery_time": "20-30 min",
        "delivery_fee": 10,
    },
    {
        "name": "il Gusto",
        "description": "Italian flavours, fresh pastas and wood-fired pizzas.",
        "address": "175 Bd Tarik Ibn Ziyad",
        "city": "Al Hoceima",
        "phone": "+212 539 000 011",
        "category": "Restaurant",
        "rating": 4.4,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGzLnxYW0v8LnnCfXjXyzTXbgjkE9U5mCTtCQkl3Kvw4giOP34Fr9cNMMUXtOLJZMvYWTB8VD3JrsKZi7uhYGZYUAbbmXYwTYW7oiGAA8oOgkgFdzciApPq2A3XYhEQdTwVB9C20XPj4GJd=w400-h400-n-k-no",
        "delivery_time": "25-35 min",
        "delivery_fee": 15,
    },
    {
        "name": "Restaurant Salsa",
        "description": "Mediterranean & Italian cuisine in the heart of Al Hoceima.",
        "address": "18 Rue 9 Juillet",
        "city": "Al Hoceima",
        "phone": "+212 539 000 012",
        "category": "Restaurant",
        "rating": 4.1,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEzFZ3R7OEwAZ7GdnO1bpohzvZBjH4MXIZU3y-gvIcHEgW0KU4BLYiwXx0k7ESaDiqwRZ1fQtEJE1rpY57D3Ti1nrWLCdJG4Lq_BMFWNrqaZsdgbYkRrUP7jpAWCnPMiF2PrIuz4Iu4NyYU=w400-h400-n-k-no",
        "delivery_time": "25-40 min",
        "delivery_fee": 15,
    },
    # ── CAFÉS ──
    {
        "name": "Gamma Le Café des Temps",
        "description": "Cozy café on Rue de Rabat — perfect for morning coffee and pastries.",
        "address": "Rue de Rabat",
        "city": "Al Hoceima",
        "phone": "+212 539 000 020",
        "category": "Café",
        "rating": 4.8,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHu_OUDxm4EdLZz9sC-mf52JG24fNJbBZEa25IGpRPIR1-SarDIiQlxPfGLM-xFXipfDzfEVMaF3do3yMgX8Go6ZZnowRFD3CRVdh8sYEm4sJX9CQvg4TRHvYdTSqsmY8v2z68=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 10,
    },
    {
        "name": "Jawhara Coffee",
        "description": "Popular café with great atmosphere and the best espresso in town.",
        "address": "Rue Hajra Nekour",
        "city": "Al Hoceima",
        "phone": "+212 539 000 021",
        "category": "Café",
        "rating": 4.7,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH4r0pRt9_yWyOWiy-tRtBk1r7lTWVsh0i6BGgm_yoQcyaZAJyrQyXZKuIqddYTd_kXDCn61gUHfvtG7W_Zmx6mBHXGlegO4g-W2auHXXzybS8w29veBE0WkesSJqtmZOFVhJU-=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 10,
    },
    {
        "name": "Espace Eucalyptus",
        "description": "Bright and welcoming coffee shop open from 6:30 AM.",
        "address": "Al Hoceima",
        "city": "Al Hoceima",
        "phone": "+212 539 000 022",
        "category": "Café",
        "rating": 4.8,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGI8rywFwzCRA9-Umg9OBbDLQJp7nNm73FQwa_x7fKau3gS_JUKciS1c2I3Z43HMRDG9DX7SyvlQPB0DOHAof39WMlqm3Q_MSDWtEoTtcYXGMWWWPGFYPjNF7t_2IHQU0NPFL7C=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 10,
    },
    {
        "name": "Délicafé",
        "description": "Most reviewed café in Al Hoceima — pastries, coffee & Moroccan breakfast.",
        "address": "78 Rue Bir Anzarane",
        "city": "Al Hoceima",
        "phone": "+212 539 000 023",
        "category": "Café",
        "rating": 4.2,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH1tMsWBuYrpipZz_SH8_2QrJsVZssCtVBwRl4KVsu83x9txLfckMmIOhEVgzeHiQDd8TWQ9AwtmgNWsF-zZXl_SkMWZlp_W2AVGvPUFpS3O_COqQdaHxcVuGzNNONsH7U4nEX4=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 10,
    },
    {
        "name": "Dolshelato",
        "description": "Artisan gelato, frappés & smoothies — open from 3PM.",
        "address": "123 Bd Abdelkarim El Khattabi",
        "city": "Al Hoceima",
        "phone": "+212 539 000 024",
        "category": "Café",
        "rating": 4.9,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE42yCfISltzwub3ZzQGl7xduDKcVaOHXdpKJtu5K7_9qEFft-kLUK5FHPLlHMXm1MR2sFR2mtZyELRsNmrkZjj-nZeSdVGlIlHr9I8unthTUI_tUAp0yzhQhphLP5lQF_yf6pQ=w400-h400-n-k-no",
        "delivery_time": "20-30 min",
        "delivery_fee": 10,
    },
    {
        "name": "Sky Blue Cafe",
        "description": "Open 24 hours — your go-to café day and night on Bd Tarik.",
        "address": "Bd Tarik Ibn Ziyad",
        "city": "Al Hoceima",
        "phone": "+212 539 000 025",
        "category": "Café",
        "rating": 4.4,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHhU4YYFyYVAp7HU-xuaYepUZkijGKomxNCjQYzmCIK8wC3sIjPfAvz7Hu4eptgTl079QelrdScDxUtrRM_7DMIuzRL8mhPkzC6fW6bvvFnLstPhC8MeA=w400-h400-n-k-no",
        "delivery_time": "15-25 min",
        "delivery_fee": 0,
    },
    # ── SUPERMARKETS ──
    {
        "name": "Supermarché Asaidi",
        "description": "Full supermarket with fresh products, groceries and household essentials.",
        "address": "Al Hoceima",
        "city": "Al Hoceima",
        "phone": "+212 539 000 030",
        "category": "Supermarket",
        "rating": 4.1,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEkGIUVuhJMZQQG8fyeLFYWbqhGJmAa2JscKzhTPsqbNGPTYH3E7HGISRyP3LlQlClRcwrqigTfO9Bo5GojTZUe8QPeLfYEpx8iBSclpQweP8B3sstNUjIsN00aARnBPM38Pg4J=w400-h400-n-k-no",
        "delivery_time": "30-45 min",
        "delivery_fee": 20,
    },
    {
        "name": "Mini Market Amrouss",
        "description": "Open 24/7 mini market — everything you need delivered fast.",
        "address": "Rue Jaber Ibn Hayane",
        "city": "Al Hoceima",
        "phone": "+212 539 000 031",
        "category": "Supermarket",
        "rating": 4.9,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFmFjt-mlQTMf7I4HORn4GncgDNgtC5OK8RKi2PMbK398DpKhKZMgzW9CVuFJB1r5Ch4N59VIhT5BmtelkO4HhUf-cVSAYXInN4BnryLu1uLBF0MporFAb1IRdcdW_pf8P0hRL=w400-h400-n-k-no",
        "delivery_time": "20-35 min",
        "delivery_fee": 15,
    },
    {
        "name": "Oujabar Market",
        "description": "Open 24/7 — fresh groceries and daily essentials delivered to your door.",
        "address": "Rue Essaouira",
        "city": "Al Hoceima",
        "phone": "+212 539 000 032",
        "category": "Supermarket",
        "rating": 4.2,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEutNNDc5egCiNJz_4GzZis3zhRzpMNolZqdLandXdxFjYjfxdTAAfAN8hQ85LQfddTWxcIL7Wm9ox6vceIC32Pt1ZZX-Cil9OMuotAddaLnwabqFnWztN-MziMlu0E9wWKRVlT=w400-h400-n-k-no",
        "delivery_time": "20-35 min",
        "delivery_fee": 15,
    },
    {
        "name": "NightShop Parki ChiTa",
        "description": "Your 24/7 night shop — snacks, drinks and all your late-night essentials.",
        "address": "Rue Hajrat Nekor",
        "city": "Al Hoceima",
        "phone": "+212 539 000 033",
        "category": "Supermarket",
        "rating": 4.8,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGv7ZhOy0HzJGDeJygGh2WurxeBNFnSAn_ItXZYfADNrTLYAEbmfWXJf2BZAqWXltgxcbI9MvhYON9GAkZoW1Z3CG2NeYygAOJ02Wsb0bPHqK4ru8CE653RYgJwWfgL5yCT3TZo9Q=w400-h400-n-k-no",
        "delivery_time": "20-30 min",
        "delivery_fee": 15,
    },
    {
        "name": "Market El Idrissi",
        "description": "Well-stocked market open until midnight — quality products at good prices.",
        "address": "Al Hoceima",
        "city": "Al Hoceima",
        "phone": "+212 539 000 034",
        "category": "Supermarket",
        "rating": 4.6,
        "is_open": True,
        "image_url": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH8hHLnV5fIbWaUiNpezcKAKAIyf7y4bAuoVXPln_Gl5wUQHMurLVSSbAjWGVD4LWsiytuZYYbD3mEXel5gLxTplcT5nsTjYUg5cmXnACbyWPlba4hPrbkJf-XL-R5jZSCsRFwU=w400-h400-n-k-no",
        "delivery_time": "25-40 min",
        "delivery_fee": 20,
    },
]

MENU_ITEMS = {
    "Casa Bento": [
        {"name": "Bento Box Poulet", "description": "Riz, poulet grillé, légumes sautés, sauce teriyaki", "price": 65, "category": "Plats"},
        {"name": "Bento Box Bœuf", "description": "Riz, bœuf mariné, légumes, sauce soja", "price": 75, "category": "Plats"},
        {"name": "Bento Végétarien", "description": "Riz, légumes grillés, tofu, sauce miso", "price": 55, "category": "Plats"},
        {"name": "Salade Fraîche", "description": "Salade composée maison avec vinaigrette", "price": 30, "category": "Entrées"},
        {"name": "Soupe du Jour", "description": "Soupe maison selon arrivage", "price": 25, "category": "Entrées"},
        {"name": "Jus d'Orange Pressé", "description": "100% frais", "price": 20, "category": "Boissons"},
        {"name": "Eau Minérale", "description": "50cl", "price": 8, "category": "Boissons"},
        {"name": "Soda", "description": "Coca-Cola / Fanta / Sprite 33cl", "price": 12, "category": "Boissons"},
    ],
    "Rico": [
        {"name": "Brochettes Mixtes", "description": "Viande hachée + kefta grillées, pain + salade inclus", "price": 45, "category": "Grillades"},
        {"name": "Poulet Grillé 1/2", "description": "Demi-poulet mariné avec frites et salade", "price": 55, "category": "Grillades"},
        {"name": "Poulet Grillé Entier", "description": "Poulet entier avec frites et salade", "price": 95, "category": "Grillades"},
        {"name": "Merguez x4", "description": "4 merguez grillées avec sauce harissa", "price": 35, "category": "Grillades"},
        {"name": "Kefta x4", "description": "4 brochettes kefta épicées", "price": 40, "category": "Grillades"},
        {"name": "Frites", "description": "Portion généreuse maison", "price": 15, "category": "Accompagnements"},
        {"name": "Salade Marocaine", "description": "Tomates, concombre, olives, huile d'argan", "price": 20, "category": "Accompagnements"},
        {"name": "Soda", "description": "Coca-Cola / Fanta / Sprite", "price": 12, "category": "Boissons"},
        {"name": "Eau Minérale", "description": "50cl", "price": 8, "category": "Boissons"},
    ],
    "Boom Burger": [
        {"name": "Classic Burger", "description": "Steak haché 150g, cheddar, salade, tomate, cornichons", "price": 45, "category": "Burgers"},
        {"name": "Double Smash Burger", "description": "Double steak smashé 300g, sauce spéciale maison", "price": 65, "category": "Burgers"},
        {"name": "Crispy Chicken Burger", "description": "Poulet croustillant, mayo épicée, pickles, chou", "price": 50, "category": "Burgers"},
        {"name": "Cheese Burger XL", "description": "Triple steak, triple cheddar, sauce BBQ", "price": 75, "category": "Burgers"},
        {"name": "Frites Maison", "description": "Frites fraîches croustillantes", "price": 18, "category": "Accompagnements"},
        {"name": "Onion Rings", "description": "Rondelles d'oignon panées", "price": 20, "category": "Accompagnements"},
        {"name": "Milkshake Vanille", "description": "Épais et crémeux", "price": 28, "category": "Boissons"},
        {"name": "Milkshake Chocolat", "description": "Chocolat belge intense", "price": 28, "category": "Boissons"},
        {"name": "Soda", "description": "33cl", "price": 12, "category": "Boissons"},
    ],
    "تاكوس الحسيمة": [
        {"name": "Tacos Poulet", "description": "Tortilla, poulet grillé, fromage fondu, sauce blanche", "price": 35, "category": "Tacos"},
        {"name": "Tacos Bœuf", "description": "Tortilla, viande hachée, légumes, sauce BBQ", "price": 40, "category": "Tacos"},
        {"name": "Tacos Mixte", "description": "Tortilla, poulet + bœuf, double sauce", "price": 45, "category": "Tacos"},
        {"name": "Tacos XL Mixte", "description": "Grand format — poulet + bœuf + kefta", "price": 60, "category": "Tacos"},
        {"name": "Nachos", "description": "Chips tortilla avec sauce fromage et jalapeños", "price": 25, "category": "Snacks"},
        {"name": "Soda", "description": "33cl", "price": 10, "category": "Boissons"},
        {"name": "Eau Minérale", "description": "50cl", "price": 7, "category": "Boissons"},
    ],
    "il Gusto": [
        {"name": "Pizza Margherita", "description": "Sauce tomate maison, mozzarella fior di latte, basilic", "price": 55, "category": "Pizzas"},
        {"name": "Pizza 4 Fromages", "description": "Mozzarella, cheddar, gouda, parmesan", "price": 70, "category": "Pizzas"},
        {"name": "Pizza Poulet BBQ", "description": "Sauce BBQ, poulet grillé, oignons, poivrons", "price": 65, "category": "Pizzas"},
        {"name": "Pâtes Carbonara", "description": "Spaghetti, lardons fumés, crème, parmesan, oeuf", "price": 50, "category": "Pâtes"},
        {"name": "Pâtes Bolognaise", "description": "Tagliatelle, sauce viande maison mijotée", "price": 50, "category": "Pâtes"},
        {"name": "Pâtes Arrabiata", "description": "Penne, sauce tomate épicée, ail, basilic", "price": 45, "category": "Pâtes"},
        {"name": "Tiramisu Maison", "description": "Dessert Italien classique", "price": 30, "category": "Desserts"},
        {"name": "Panna Cotta", "description": "Crème cuite, coulis de fruits rouges", "price": 28, "category": "Desserts"},
        {"name": "Eau Minérale", "description": "50cl", "price": 8, "category": "Boissons"},
        {"name": "Jus d'Orange", "description": "Pressé frais", "price": 22, "category": "Boissons"},
    ],
    "Jawhara Coffee": [
        {"name": "Café Noir", "description": "Espresso simple ou double — arabica sélectionné", "price": 12, "category": "Cafés"},
        {"name": "Café au Lait", "description": "Espresso + lait chaud en mousse", "price": 18, "category": "Cafés"},
        {"name": "Cappuccino", "description": "Espresso, lait mousse, saupoudré de cacao", "price": 22, "category": "Cafés"},
        {"name": "Latte Noisette", "description": "Espresso, lait vapeur, sirop noisette", "price": 25, "category": "Cafés"},
        {"name": "Café Glacé", "description": "Espresso sur glace avec lait", "price": 28, "category": "Cafés"},
        {"name": "Thé à la Menthe", "description": "Thé vert avec menthe fraîche et sucre", "price": 12, "category": "Thés"},
        {"name": "Croissant Beurre", "description": "Croissant pur beurre frais du matin", "price": 15, "category": "Viennoiseries"},
        {"name": "Pain au Chocolat", "description": "Feuilleté au chocolat noir", "price": 15, "category": "Viennoiseries"},
        {"name": "Muffin Myrtille", "description": "Muffin moelleux aux myrtilles", "price": 18, "category": "Viennoiseries"},
    ],
    "Délicafé": [
        {"name": "Espresso", "description": "Court et intense, arabica 100%", "price": 10, "category": "Cafés"},
        {"name": "Américain", "description": "Espresso allongé à l'eau chaude", "price": 15, "category": "Cafés"},
        {"name": "Café Crème", "description": "Espresso + crème fraîche légère", "price": 20, "category": "Cafés"},
        {"name": "Thé à la Menthe", "description": "Thé vert avec menthe fraîche et sucre", "price": 12, "category": "Thés"},
        {"name": "Thé Vert Nature", "description": "Thé vert de Chine sans sucre", "price": 10, "category": "Thés"},
        {"name": "Jus d'Orange Frais", "description": "Pressé minute", "price": 20, "category": "Jus"},
        {"name": "Jus de Pomme", "description": "100% naturel", "price": 18, "category": "Jus"},
        {"name": "Msemen + Miel", "description": "Galette feuilletée marocaine avec miel de fleurs", "price": 18, "category": "Petit-déjeuner"},
        {"name": "Harcha", "description": "Pain semoule avec fromage ou miel", "price": 15, "category": "Petit-déjeuner"},
        {"name": "Beghrir + Beurre", "description": "Crêpes mille-trous avec beurre fondu et miel", "price": 20, "category": "Petit-déjeuner"},
    ],
    "Dolshelato": [
        {"name": "Gelato 1 Boule", "description": "Vanille / Chocolat / Pistache / Fraise — au choix", "price": 18, "category": "Glaces"},
        {"name": "Gelato 2 Boules", "description": "2 parfums au choix dans un cornet ou une coupe", "price": 30, "category": "Glaces"},
        {"name": "Gelato 3 Boules", "description": "3 parfums dans une grande coupe", "price": 40, "category": "Glaces"},
        {"name": "Sundae Caramel", "description": "3 boules + sauce caramel + chantilly + noix", "price": 45, "category": "Spécialités"},
        {"name": "Sundae Chocolat", "description": "3 boules + sauce chocolat chaud + amandes", "price": 45, "category": "Spécialités"},
        {"name": "Café Frappé", "description": "Espresso glacé avec lait et sirop", "price": 28, "category": "Cafés glacés"},
        {"name": "Frappuccino Caramel", "description": "Café glacé, caramel, chantilly", "price": 32, "category": "Cafés glacés"},
        {"name": "Smoothie Fruits Rouges", "description": "Fraise, framboise, myrtille, lait de coco", "price": 32, "category": "Smoothies"},
        {"name": "Smoothie Mangue-Passion", "description": "Mangue, fruit de la passion, banane", "price": 32, "category": "Smoothies"},
    ],
    "Supermarché Asaidi": [
        {"name": "Lait Centrale 1L", "description": "Lait entier pasteurisé", "price": 9, "category": "Produits laitiers"},
        {"name": "Yaourt Danone x4", "description": "Yaourt nature 125g x4", "price": 18, "category": "Produits laitiers"},
        {"name": "Fromage Kiri x8", "description": "Portions fondantes", "price": 22, "category": "Produits laitiers"},
        {"name": "Pain de Mie", "description": "500g tranché", "price": 12, "category": "Boulangerie"},
        {"name": "Œufs Frais x6", "description": "Calibre moyen, frais du jour", "price": 15, "category": "Produits frais"},
        {"name": "Eau Sidi Ali 1.5L", "description": "Eau minérale naturelle", "price": 8, "category": "Boissons"},
        {"name": "Coca-Cola 1.25L", "description": "Boisson gazeuse", "price": 16, "category": "Boissons"},
        {"name": "Jus Marafiq 1L", "description": "Orange / Pêche / Mangue", "price": 18, "category": "Boissons"},
        {"name": "Chips Lay's 90g", "description": "Nature / BBQ / Paprika", "price": 10, "category": "Snacks"},
        {"name": "Chocolat Milka 100g", "description": "Lait / Noisette / Caramel", "price": 22, "category": "Snacks"},
    ],
    "Mini Market Amrouss": [
        {"name": "Eau Minérale 1.5L", "description": "Sidi Ali ou Ain Sais", "price": 7, "category": "Boissons"},
        {"name": "Soda 33cl", "description": "Coca / Fanta / Sprite / Pepsi", "price": 10, "category": "Boissons"},
        {"name": "Jus Marafiq 1L", "description": "Orange / Pomme / Mangue", "price": 18, "category": "Boissons"},
        {"name": "Chips Lay's", "description": "Sachet 90g — différents parfums", "price": 10, "category": "Snacks"},
        {"name": "Barre Chocolat", "description": "Kinder / Milka / Twix / Kit Kat", "price": 8, "category": "Snacks"},
        {"name": "Cacahuètes Grillées", "description": "Sachet 100g salé", "price": 8, "category": "Snacks"},
        {"name": "Café Nescafé 3-en-1", "description": "Sachet individuel", "price": 5, "category": "Boissons chaudes"},
        {"name": "Lait Centrale 1L", "description": "Lait entier", "price": 9, "category": "Épicerie"},
        {"name": "Œufs x6", "description": "Frais du jour", "price": 15, "category": "Épicerie"},
    ],
    "Oujabar Market": [
        {"name": "Pack Eau x6 (50cl)", "description": "6 bouteilles d'eau minérale", "price": 35, "category": "Boissons"},
        {"name": "Lait 1L", "description": "Centrale / Jaouda entier", "price": 9, "category": "Produits laitiers"},
        {"name": "Beurre Président 200g", "description": "Beurre doux", "price": 28, "category": "Produits laitiers"},
        {"name": "Confiture Savane 370g", "description": "Fraise / Abricot / Orange", "price": 22, "category": "Épicerie"},
        {"name": "Huile Cristal 1L", "description": "Huile de tournesol", "price": 35, "category": "Épicerie"},
        {"name": "Sac de Pommes de Terre 1kg", "description": "Fraîches, idéales pour frites", "price": 12, "category": "Légumes"},
        {"name": "Tomates 500g", "description": "Fraîches de saison", "price": 8, "category": "Légumes"},
        {"name": "Détergent Ariel 1kg", "description": "Lessive en poudre", "price": 45, "category": "Entretien"},
    ],
    "NightShop Parki ChiTa": [
        {"name": "Soda 33cl", "description": "Coca / Fanta / Sprite — frais du frigo", "price": 12, "category": "Boissons"},
        {"name": "Energy Drink", "description": "Red Bull / Burn 250ml", "price": 20, "category": "Boissons"},
        {"name": "Eau Minérale 1.5L", "description": "Fraîche", "price": 8, "category": "Boissons"},
        {"name": "Chips", "description": "Lay's / Vico / Papas — différents formats", "price": 10, "category": "Snacks"},
        {"name": "Sandwich Jambon-Fromage", "description": "Pain de mie grillé, prêt à manger", "price": 18, "category": "Sandwichs"},
        {"name": "Pizza Individuelle", "description": "Réchauffée minute — fromage ou mixte", "price": 25, "category": "Plats rapides"},
        {"name": "Cigarettes Marlboro", "description": "Pack de 20", "price": 35, "category": "Tabac"},
        {"name": "Allumettes / Briquet", "description": "Briquet jetable", "price": 5, "category": "Divers"},
    ],
    "Market El Idrissi": [
        {"name": "Lait Frais 1L", "description": "Centrale ou Jaouda", "price": 9, "category": "Produits laitiers"},
        {"name": "Fromage Vache Qui Rit x8", "description": "Portions fondantes", "price": 25, "category": "Produits laitiers"},
        {"name": "Pain Khobz", "description": "2 pains ronds marocains", "price": 5, "category": "Boulangerie"},
        {"name": "Thon Saupiquet 160g", "description": "Au naturel ou à l'huile", "price": 22, "category": "Conserves"},
        {"name": "Harira (bocal)", "description": "Soupe marocaine prête à chauffer", "price": 28, "category": "Conserves"},
        {"name": "Riz Basmati 1kg", "description": "Grain long parfumé", "price": 25, "category": "Épicerie sèche"},
        {"name": "Pâtes Macaroni 500g", "description": "Barilla ou équivalent", "price": 15, "category": "Épicerie sèche"},
        {"name": "Savon Ach Brita", "description": "Pack x4", "price": 18, "category": "Hygiène"},
    ],
}


class Command(BaseCommand):
    help = 'Seed the database with real Al Hoceima restaurants and menu items'

    def handle(self, *args, **kwargs):
        created_count = 0
        skipped_count = 0

        for r_data in RESTAURANTS:
            image_url = r_data.pop("image_url", "")
            delivery_time = r_data.pop("delivery_time", "25-40 min")
            delivery_fee = r_data.pop("delivery_fee", 15)

            restaurant, created = Restaurant.objects.get_or_create(
                name=r_data["name"],
                defaults={
                    **r_data,
                    "description": r_data.get("description", ""),
                }
            )

            if created:
                created_count += 1
                self.stdout.write(f"  ✅ Created: {restaurant.name}")

                # Add menu items
                items = MENU_ITEMS.get(r_data["name"], [])
                for item in items:
                    MenuItem.objects.create(
                        restaurant=restaurant,
                        name=item["name"],
                        description=item.get("description", ""),
                        price=item["price"],
                        category=item["category"],
                        is_available=True,
                    )
                self.stdout.write(f"     → {len(items)} menu items added")
            else:
                skipped_count += 1
                self.stdout.write(f"  ⏭️  Skipped (already exists): {restaurant.name}")

        self.stdout.write(self.style.SUCCESS(
            f"\n🎉 Done! {created_count} restaurants created, {skipped_count} skipped."
        ))
